version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: Theather_DataBase
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydatabase
    ports:
      - "5532:5432"
    volumes:
      - $PWD/postgresTheatre_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminTheatre
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "4040:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
