version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydatabase
    ports:
      - "5532:5432"  # Expose port 5432 from the container to port 5532 on your host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # Expose port 80 from pgAdmin to port 5050 on your host
    depends_on:
      - postgres

volumes:
  postgres_data:
